---
- name: Deploy a new VM from a template
  hosts: localhost
  gather_facts: no
  vars_files:
    - secrets.yml
  tasks:
    - name: Deploy VM from template
      community.vmware.vmware_guest:
        hostname: "192.168.1.44"  # vCenter or ESXi host managing the deployment
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        datacenter: "lab01"  # Matches your folder
        folder: ""  # Root folder under the datacenter
        esxi_hostname: "192.168.1.43"  # Host where the template resides
        template: "template_VM"  # Template name
        name: "from_Ansible"  # new VM name
        disk:
          - size_gb: 20  # Adjust if needed
            datastore: "datastore1"  # Target datastore
            type: "thin"  # Use "thin" or match the format of the source
        hardware:
          memory_mb: 2048  # Memory size in MB
          num_cpus: 2  # Number of CPUs
        networks:
          - name: "VM Network"  # Network name as configured in vSphere
            type: "dhcp"  # Use "dhcp" or configure a static IP
            connected: true  # Ensures the adapter is connected at power-on
        state: present