apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flaskapp-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: webapp
  namespaceSelector:
    matchNames:
      - app-v1
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
