# --- Deployment ---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: app-v1
  labels: { app: webapp }
spec:
  replicas: 2
  selector: { matchLabels: { app: webapp } }
  template:
    metadata:
      labels: { app: webapp }
    spec:
      containers:
        - name: webapp
          image: docker.io/angsdocker/web-app:v1
          ports: [{ containerPort: 8000 }]
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits: { cpu: "500m", memory: "512Mi" }

---
# --- Service ---

apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: app-v1
  labels: { app: webapp }
spec:
  selector: { app: webapp }
  ports:
    - name: http
      port: 80
      targetPort: 8000

---
# --- Ingress ---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp
  namespace: app-v1
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: homelab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webapp
                port:
                  number: 80
