---
- name: Install Kubernetes components on AWS EC2
  hosts: aws
  become: yes
  tasks:

    - name: Disable swap (required for Kubernetes)
      command: swapoff -a
      when: ansible_swaptotal_mb > 0
      ignore_errors: true

    - name: Ensure swap is disabled permanently
      replace:
        path: /etc/fstab
        regexp: '(^.*swap.*$)'
        replace: '# \1'
      ignore_errors: true

    - name: Load required kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Set up sysctl params for Kubernetes networking
      copy:
        dest: /etc/sysctl.d/kubernetes.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1

    - name: Apply sysctl params
      command: sysctl --system

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
        state: present
        update_cache: yes

    - name: Add Kubernetes apt key (modern method)
      shell: |
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes apt repository (modern method)
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"

    # 👇 ADD THIS TASK
    - name: Update apt cache after adding Kubernetes repo
      apt:
        update_cache: yes
    # 👆 ensures apt knows about the new repo

    - name: Install kubelet, kubeadm, and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Hold Kubernetes package versions
      command: apt-mark hold kubelet kubeadm kubectl

    - name: Enable and start kubelet service
      service:
        name: kubelet
        enabled: yes
        state: started

    - name: Verify kubeadm installation
      command: kubeadm version -o short
      register: kubeadm_version
      ignore_errors: true

    - name: Verify kubectl installation
      command: kubectl version --client --short
      register: kubectl_version
      ignore_errors: true

    - name: Print versions
      debug:
        msg:
          - "kubeadm version: {{ kubeadm_version.stdout | default('not found') }}"
          - "kubectl version: {{ kubectl_version.stdout | default('not found') }}"
